[package]
name = "idlset"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]

description = "Fast u64 set operations library"
documentation = "https://docs.rs/idlset/0.1.0/idlset/"
homepage = "https://github.com/Firstyear/idlset/"
repostiory = "https://github.com/Firstyear/idlset/"
readme = "README.md"
keywords = ["data-structures", "sets", "compression", "u64"]
categories = ["data-structures", "algorithms", "compression"]
license = " LGPL-3.0-only"
license-file = "LICENSE.md"

[dependencies]
time = "0.1"

[[bin]]
name = "bench_idl"
path = "src/bench.rs"

